spring.application.name=football-league-app
spring.datasource.url=jdbc:postgresql://localhost:5432/football_league
spring.datasource.username=postgres
spring.datasource.password=Tomohawk25!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
